// Copyright 2023 - 2024 Ossi Luoto, 2025 Torphedo
// 
// Datamoshing compute shader

#include "/Engine/Public/Platform.ush"
#include "/Engine/Private/Common.ush"

// Default border size for group.
#define DEFAULT_GROUP_BORDER_SIZE 8
#define GROUP_BORDER_SIZE (DEFAULT_GROUP_BORDER_SIZE)

// Shader parameters

// SceneColor texture
Texture2D OriginalSceneColor;
Texture2D Velocity;
Texture2D DepthTex;

// Viewport size
uint4 ViewportRect;

// This is the UV for Viewport
float2 ViewportInvSize;

// This is the multiplier to scale Viewport UV (0..1) to current SceneColor RT
float2 SceneColorUVScale;

// TODO: Document these
float4x4 curr_screen_to_world;
float4x4 prev_world_to_screen;

// Output
RWTexture2D<float4> historyBuffer;

float2 viewport_velocity(float2 viewportUV, float depth, float4x4 inv_view_proj, float4x4 prev_view_proj) {
	// Velocity calculation from GPU Gems 3 motion blur velocity:
	// https://developer.nvidia.com/gpugems/gpugems3/part-iv-image-effects/chapter-27-motion-blur-post-processing-effect
	
	// Map back to clip space
	const float4 clip_coord = float4(viewportUV.x * 2 - 1, (1 - viewportUV.y) * 2 - 1, depth, 1.0f);

	// Transform to world space
	float4 world_coord = mul(clip_coord, inv_view_proj);
	world_coord /= world_coord.w; // Perspective division (?)

	// Transform back to clip space using last frame's view-projection matrix
	float4 prev_clip_coord = mul(world_coord, prev_view_proj);
	prev_clip_coord /= prev_clip_coord.w;

	// Take distance, and undo our multiplication from earlier
	return (clip_coord - prev_clip_coord) / 2.0f;
}

// Compute Shader code
[numthreads(GROUP_BORDER_SIZE, GROUP_BORDER_SIZE, 1)]
void MainCS(uint2 DispatchThreadId : SV_DispatchThreadID) {
	// Check that we are in scope
	if (any(DispatchThreadId >= ViewportRect.zw)) {
		return;
	}

	// If we have the Original Scene Color still here, we need to use the original offset as well
	// Due to UniformBuffer referring to the Viewport before TAA (this might change in the future?) we need to apply scale to the UV
	float2 sampleUV = (float2(View.ViewRectMin.xy) + (DispatchThreadId + 0.5)) * ViewportInvSize;
	float2 outputUV = View.ViewRectMin.xy + DispatchThreadId;

	// At this point our sampleUV is mapped to 0..1
	// This is the UV value one might want to use if f.ex. altering the coordinates via shader formula

	// As the actual viewport might not utilize the full texture, we need to scale accordingly - see calculation on the .cpp side
	sampleUV = sampleUV * SceneColorUVScale;

	// Sample textures
	float4 OriginalColor = OriginalSceneColor.SampleLevel(GlobalPointClampedSampler, sampleUV, 0);
	float4 velocityColor = Velocity.SampleLevel(GlobalPointClampedSampler, sampleUV, 0);
	float depthColor = DepthTex.SampleLevel(GlobalPointClampedSampler, sampleUV, 0);

	// Calculate screen-space object movement
	float2 screen_diff = viewport_velocity(sampleUV, depthColor, curr_screen_to_world, prev_world_to_screen);
	// Leave the skybox alone
	if (depthColor < 0.00001f) {
		screen_diff = 0;	
	}
	
	// Only use our velocity if the engine doesn't provide one
	screen_diff *= length(velocityColor) == 0;

	velocityColor.rg *= SceneColorUVScale;

	if (length(velocityColor.rg) > 0 && length(screen_diff) == 0) {
        screen_diff.x = velocityColor.r;
        screen_diff.y = velocityColor.g;
	}
	
	// Visualize motion vectors in output color
	// OriginalColor.rgb = float3(screen_diff, 0.0f); screen_diff = 0;
	
	// Write output
	float2 motionUV = outputUV + screen_diff;
	float2 inv_motionUV = outputUV - screen_diff;

	// Copy current frame to history, then distort. If the CPU set the history buffer as the scene color, this only
	// distorts.
	historyBuffer[outputUV] = OriginalColor;
	if (motionUV.x != outputUV.x || motionUV.y != outputUV.y) {
		historyBuffer[inv_motionUV] = historyBuffer[motionUV];
		historyBuffer[outputUV] = historyBuffer[motionUV];
	}
	
	// Visualize motion vectors on top of the normal frame
	// historyBuffer[outputUV] = OriginalColor + 0.5 * float4(screen_diff, 0, 1);
}