// Copyright 2023 - 2024 Ossi Luoto, 2025 Torphedo
// 
// Datamoshing compute shader

#include "/Engine/Public/Platform.ush"
#include "/Engine/Private/Common.ush"

// Default border size for group.
#define DEFAULT_GROUP_BORDER_SIZE 8
#define GROUP_BORDER_SIZE (DEFAULT_GROUP_BORDER_SIZE)

// Shader parameters

// SceneColor texture
Texture2D OriginalSceneColor;
Texture2D Velocity;

// Viewport size
uint4 ViewportRect;

// This is the UV for Viewport
float2 ViewportInvSize;

// This is the multiplier to scale Viewport UV (0..1) to current SceneColor RT
float2 SceneColorUVScale;

// TODO: Document these
float4x4 prev_screen_to_world;
float4x4 curr_screen_to_world;
float4x4 world_to_screen;

// Output
RWTexture2D<float4> Output;
RWTexture2D<float4> historyBuffer;

// Compute Shader code
[numthreads(GROUP_BORDER_SIZE, GROUP_BORDER_SIZE, 1)]
void MainCS(uint2 DispatchThreadId : SV_DispatchThreadID) {
	// Check that we are in scope
	if (any(DispatchThreadId >= ViewportRect.zw)) {
		return;
	}

	// If we have the Original Scene Color still here, we need to use the original offset as well
	// Due to UniformBuffer referring to the Viewport before TAA (this might change in the future?) we need to apply scale to the UV
	float2 sampleUV = (float2(View.ViewRectMin.xy) + (DispatchThreadId + 0.5)) * ViewportInvSize;
	float2 outputUV = (View.ViewRectMin.xy + DispatchThreadId);

	// At this point our sampleUV is mapped to 0..1
	// This is the UV value one might want to use if f.ex. altering the coordinates via shader formula

	// As the actual viewport might not utilize the full texture, we need to scale accordingly - see calculation on the .cpp side
	sampleUV = sampleUV * SceneColorUVScale;

	float4 OriginalColor = OriginalSceneColor.SampleLevel(GlobalPointClampedSampler, sampleUV, 0);

	float4 velocityColor = Velocity.SampleLevel(GlobalPointClampedSampler, sampleUV, 0);
	bool has_motion = length(velocityColor.r) > 0 && velocityColor.g > 0;
	if (!has_motion) {
		float4 screen_point = float4(outputUV, 0.0f, 1.0f);
		float4 prev_pos = mul(prev_screen_to_world, screen_point);
		float4 curr_pos = mul(curr_screen_to_world, screen_point);
		float4 screen_diff = mul(world_to_screen, curr_pos - prev_pos);
		
		velocityColor = screen_diff;
		has_motion = length(velocityColor.r) > 0 && velocityColor.g > 0;
	}

	// float2 prev_world_pos = sampleUV * prev_screen_to_world;
	// float2 curr_world_pos = sampleUV * curr_screen_to_world;
	
	// Map velocity down to more reasonable vector values
	velocityColor = has_motion * (velocityColor - 0.5f);

	// Visualize motion vectors on top of the normal frame
	// OriginalColor.rg += 0.1 * velocityColor.rg;

	// Visualize motion vectors in output color
	// OriginalColor = float4(velocityColor.rg, 0, 0);

	// Write output
	float2 motionUV = outputUV + (1 * (velocityColor.rg));
	Output[outputUV] = OriginalColor;
	Output[motionUV] = OriginalColor;
	// historyBuffer[outputUV] = float4(0, 0, 0, 0);
	// Output[outputUV] = (historyBuffer[outputUV] * historyBuffer[outputUV].a) + (OriginalColor * !historyBuffer[outputUV].a);

	float4 historyColor = historyBuffer[outputUV];
	historyBuffer[motionUV] = float4(OriginalColor.rgb, 1.0f * has_motion);
	return;
	if (historyColor.a) {
		Output[outputUV] = historyColor;
	} else {
		Output[outputUV] = OriginalColor;
    }

	if (has_motion) {
		// Copy moving pixels to their new location
		historyBuffer[motionUV] = float4(OriginalColor.rgb, 1.0f * has_motion);

		// Copy a new pixel to this location to make the background sort of follow the motion
		float2 inverse_motionUV = outputUV - (1 * (velocityColor.rg));
		// float4 OriginalColor = OriginalSceneColor.SampleLevel(GlobalPointClampedSampler, sampleUV, 0);
		historyBuffer[sampleUV] = OriginalSceneColor.SampleLevel(GlobalPointClampedSampler, inverse_motionUV, 0);
	}
}