// Copyright 2023 - 2024 Ossi Luoto, 2025 Torphedo
// 
// Datamoshing compute shader

#include "/Engine/Public/Platform.ush"
#include "/Engine/Private/Common.ush"

// Default border size for group.
#define DEFAULT_GROUP_BORDER_SIZE 8
#define GROUP_BORDER_SIZE (DEFAULT_GROUP_BORDER_SIZE)

// Shader parameters

// SceneColor texture
Texture2D OriginalSceneColor;
Texture2D Velocity;

// Viewport size
uint4 ViewportRect;

// This is the UV for Viewport
float2 ViewportInvSize;

// This is the multiplier to scale Viewport UV (0..1) to current SceneColor RT
float2 SceneColorUVScale;

// Output
RWTexture2D<float3> Output;

// Compute Shader code
[numthreads(GROUP_BORDER_SIZE, GROUP_BORDER_SIZE, 1)]
void MainCS(uint2 DispatchThreadId : SV_DispatchThreadID) {
	// Check that we are in scope
    if (any(DispatchThreadId >= ViewportRect.zw)) {
        return;
    }

    // If we have the Original Scene Color still here, we need to use the original offset as well
    // Due to UniformBuffer referring to the Viewport before TAA (this might change in the future?) we need to apply scale to the UV
    float2 sampleUV = (float2(View.ViewRectMin.xy) + (DispatchThreadId + 0.5)) * ViewportInvSize;

    // At this point our sampleUV is mapped to 0..1
    // This is the UV value one might want to use if f.ex. altering the coordinates via shader formula

    // As the actual viewport might not utilize the full texture, we need to scale accordingly - see calculation on the .cpp side
    sampleUV = sampleUV * SceneColorUVScale;

    float4 OriginalColor = OriginalSceneColor.SampleLevel(GlobalPointClampedSampler, sampleUV, 0);

    float4 velocityColor = Velocity.SampleLevel(GlobalPointClampedSampler, sampleUV, 0);
	// Map velocity down to more reasonable vector values
	velocityColor = (velocityColor > 0) * (velocityColor - 0.5f);

	// Visualize motion vectors on top of the normal frame
	// OriginalColor.rg += 0.1 * velocityColor.rg;

	// Visualize motion vectors in output color
	// OriginalColor = float4(velocityColor.rg, 0, 0);

    // Write output
	float2 outputUV = (View.ViewRectMin.xy + DispatchThreadId);
    // Output[outputUV] = OriginalColor;
    Output[outputUV + (200 * (velocityColor.rg))] = OriginalColor;
}